### ISSUE TITLE
./check_mtr:54:in `run_mtr': undefined method `captures' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by bbhenry** [martin2110/check_mtr#1]
Hi, I am getting the following errors

./check_mtr -H 4.2.2.2
./check_mtr:54:in `run_mtr': undefined method`captures' for nil:NilClass (NoMethodError)
    from ./check_mtr:50:in `each'
    from ./check_mtr:50:in`run_mtr'
    from ./check_mtr:11:in `initialize'
    from ./check_mtr:136:in`new'
    from ./check_mtr:136

**Comment by martin2110** [comment]
hey I never got to test this, I wrote and tested it on OSX,
It looks like the output is diffrent on linux's mtr, try this https://github.com/martin2110/check_mtr/commit/836af698ce686a6b6523376eba62406a21a1647d
